markdown: kramdown
highlighter: rouge
permalink: /blog/:title
title: "L'INFINITO"
date: Jun 6-8
year: 2018
tickets: true
tickets-eb: //eventbrite.com/tickets-external?eid=35320045206&ref=etckt
tickets-eb-link: http://kerning-2018.eventbrite.com
tickets-eb-height: 600px
speakers: true
talks: false
workshops: false
schedule: false
cfs: true
rdiscount:
  extensions: [smart]
gems:
  - jekyll-sitemap
kramdown:
  input: GFM
